name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.9.0]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install -g npm@latest
        npm install -g @angular/cli
        cd ./GitHub/demo-ui/ && npm install
        cd ./GitHub/demo-ui/ && ng build
      env:
        CI: true
